// react_framework/src/App.js
import { useRef, useState } from 'react'

function App() {

const inputRef = useRef(null)

const [name, setName] = useState('Hello World');

const handleClick = () => {
  setName(inputRef.current.value)
}

  return (
    <div className="App">
    <input type="text"
          placeholder='Message to Display'
          ref={inputRef}/>
    <button  class="btn-primary" onClick={handleClick}>Display Message</button>
    <ul>
    <h2>
      {name}
    </h2>
    </ul>
    
    </div>
  );
}

export default App;

// angular_framework/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular_framework';
  displayVal= "Hello World";
  displayVal2= '';

  getValue(val:string)
  {
    console.warn(val)
    this.displayVal= val
  }
}


<div class="main">
<input type="text"
 #box
placeholder="Message to Display"
name="name"
 id="addItemInput" />

  <button class="btn-primary" (click)="getValue(box.value)">Display Message</button>
  <ul>
  <h2>{{displayVal}}</h2>
  </ul>
 </div>
